from google.appengine.ext import db

class Game(db.Model):
  """A Game contains all the information about a ZombieRun game.
  
  A note on security: because the game state includes informaiton on some
  peoples' locations, consideration should be given to protecting the game
  state from unauthorized access (by entities that are not )"""
  
  # List of player entries.  Text-typed to avoid indexing.
  players = db.ListProperty(db.Text)

  # A secret key that must be provided for the game state to be accessed or
  # modified by a game participant. This is randomly generated by the game
  # server when the game is created and handed out to players that join the
  # game.  All game access must include this key for the server to not simply
  # return an unauthorized access status code.
  secret_keys = db.ListProperty(db.Text)
  
  # Serialized list of zombies.  Parsing and encoding is left up to the master
  # game device.
  zombies = db.TextProperty()
  
  # The game's destination.
  destination = db.TextProperty()
  
  # If true, the game has been started and no new players can join.  This is
  # a security mechanism to allow us to, at least in the future, lock down the
  # list of people who can access the game state (which includes player
  # locations).
  started = db.BooleanProperty()
  
  # Time at which this game state was last accessed or modified.  Defaults to
  # the current time.  Used for garbage collection.
  last_access_time = db.DateTimeProperty(auto_now=True)
  
  # Time at which this game state was created.
  game_creation_time = db.DateTimeProperty(auto_now_add=True)
